### ISSUE TITLE
How to load a backup from deleted world ?

### ISSUE THREAD

**Issue by 0ctoqus** [pcal43/fastback#137]
Hello guys, I'v tried creating a backup to my google drive with the create-file-remote command, I was wondering how do you go about loading the backup on another computer if the world directory is deleted on my main machine ?

The set-remote command does not list the snapshots from another world from the already existing folder.
The create-file-remote give me an error stating the backup folder already exist at the location.
Thanks.

BTW the discord invite link is broken on the documentation website.

**Comment by pcal43** [comment]
Hi.  TLDR, this part of the mod is still a WIP.  I just added a page to the docs that should help clarify:

https://pcal43.github.io/fastback/remote.html

> the discord invite link

Fixed, thanks!

**Comment by pcal43** [comment]
Ok, I've added the new commands to the new version (0.5.0) and updated the docs here:
https://pcal43.github.io/fastback/remote.html

I think that pretty well covers it so I'm going to go ahead and close this one out.  Thanks for the feedback!
