### ISSUE TITLE
Server Console | Incorrect Argument Despite Correct Formulation

### ISSUE THREAD

**Issue by ghost** [pcal43/fastback#170]
![image](https://user-images.githubusercontent.com/24266948/199640004-e5d89f7e-f4c2-4695-b16e-e1a86ede93ce.png)

If I'm not mistaken, this should be exactly the right command (based on the documentation at least).

However, it's being rejected. Is this human error or an actual issue?

EDIT: Other commands such as `backup set-autoback-action <N>` and `backup set-autoback-wait <N>` work just fine.

**Comment by ghost** [comment]
My system/game information is identical to #167.

**Comment by pcal43** [comment]
The policy got renamed but the docs are wrong.  It should be

```
backup set-retention fixed 10
```

I'll fix the docs.  Thanks for the report.
