### ISSUE TITLE
create-file-remote 

### ISSUE THREAD

**Issue by ghost** [pcal43/fastback#175]
Hello,

I recently am setting up fastback for my server. I have an ssd mounted to /mnt/ssd2, and have been attempting to place the backup file at /mnt/ssd2/db-ahptplus/backup/games/minecraft. I run the following command on my server (with OP) and I get the following error in latest.log. I have full permissions to all of the files on /mnt/ssd2. I run this server through docker with 🌐[ itzg/minecraft-server](https://github.com/itzg/docker-minecraft-server). 

Here is the error log. Any help on this would be appreciated!
https://gist.github.com/AhptIO/ed55bb3df20f4f780761bfdfe6d91f55

**Comment by pcal43** [comment]
I can really only speculate but this is almost certainly a problem with your container.  I'd double check that the user you're running the server as has permissions on the mount path.

I don't think it's a bug in fastback, in any event.

**Comment by pcal43** [comment]
You could try manually creating the directory.  But then I suspect it still won't have permissions to write files.

**Comment by pcal43** [comment]
havent heard back, closing
