### ISSUE TITLE
running `backup set-remote ...` then `backup full` fails

### ISSUE THREAD

**Issue by mrbuilder1961** [pcal43/fastback#177]
ive been trying to set up the remote connection with my google drive, through the desktop app. i've also tried symlinks, both give an error saying they don't exist. the google drive automatically sets up as a new network drive, under `G:/`. i see no reason why it wouldn't behave as a normal folder/drive.
The errors are either "URI doesnt exist" (when starting with `file://`), or the main one being '... not found'.

Log: https://mclo.gs/Mid3v1m

thanks for the mod btw!

**Comment by pcal43** [comment]
I can only suggest [researching](https://en.wikipedia.org/wiki/File_URI_scheme) the proper format for file URIs on Windows.

Also, please use the [discord](https://discord.gg/jUP5nSPrjx) channel for support issues.  Thanks.
