### ISSUE TITLE
[feature request] Actual Config File

### ISSUE THREAD

**Issue by Merith-TK** [pcal43/fastback#179]
Why not just make an actual config file? all of the issues I have had with the mod, I have had to fix using methods only available to those with *proper* access to a server files, (not sftp, im talking actually having shell access) which is an very big no go with most Server hosts

so have teh config file function like so, and have some psuedo logic from me on how it could work

1) config file has Git User, Password, and Remote address, (optional ssh-key path, default to `config/fastback/sshkey`, this would be an actual sshkey FILE, not a folder)
2) On mod load, set world remote URL to remote address, 
3) manually do the rest through the mod as such, using the variables provided in the config file

**Comment by pcal43** [comment]
Discussed on discord
https://discord.com/channels/1019626071097868289/1019626412346445844/1064770087162224641
