### ISSUE TITLE
Appears to Creates Bare Branches rather than branching off from previous

### ISSUE THREAD

**Issue by Merith-TK** [pcal43/fastback#180]
![image](https://user-images.githubusercontent.com/10422110/215191077-c5e42e46-8015-488a-b3a8-0ad16dded170.png)

From my understanding of how git should work, it should instead show more of a branching method, rather than just straight lines? (branching off from the previous branch)

By the looks of this, it appears to be making an new `bare` branch (contains no history) and then commits to that rather than branching off of the previous 

personally, if I knew how to use the library and actually code java, I would look into making the mod use tags rather than branches, (branch being `snapshots/server-uuid` with tags containing the date so its easier to track the changes through the days as git diff would actually work)

**Comment by Merith-TK** [comment]
Yeah its just making bare branches 

otherwise the diff wouldnt look like this (in the screenshot I only changed two lines between this snapshot and the last outside of region files)
![image](https://user-images.githubusercontent.com/10422110/215192914-fab4a59e-c64d-45fa-b329-3c1c58e11aac.png)


its committing as if the file is brand new and not modified

**Comment by pcal43** [comment]
This is working as intended.  Snapshots are created on orphan branches so that they can be removed and their disk space reclaimed.
