### ISSUE TITLE
Feature - Ability to disable / limit log messages

### ISSUE THREAD

**Issue by unilock** [pcal43/fastback#200]
It would be nice to be able to disable backup progress log messages, or (more realistically) to limit them such that only certain messages are shown. This would make the log file much smaller and easier to read when diagnosing server issues.

<details>
<summary>Specifically:</summary>

- Can be done without:
  - `Skipping auto-backup until at least X more minutes have elapsed.`
  - `Done Opening connection` / `Done Counting objects`
  - `Done Finding sources` / `Done Getting sizes` / `Done Compressing objects` / `Done Writing objects`
  - `Done Pack refs` / `Done Selecting commits` / `Done Building bitmaps` / `Done Prune loose objects also found in pack files` / `Done Prune loose, unreferenced objects` (gc)

- Can be limited to only show initial progress indicator (i.e. message without % completion):
  - `Finding sources ...%`
  - `Getting sizes ...%`
  - `Compressing objects ...%`
  - `Writing objects ...%`
  - `remote: Resolving deltas ...%`
  - `remote: Updating references ...%`
  - `Building bitmaps ...%` (gc)
  - `Prune loose objects also found in pack files ...%` (gc)
  - `Prune loose, unreferenced objects ...%` (gc)

</details>

This would, of course, be configurable - for example, "debug" logging mode would include all of the above messages, etc.

**Comment by NopeProsOnly** [comment]
Related:
https://github.com/pcal43/fastback/pull/203

Note: This does not add a way to disable them this is just for one ("Skipping ..."). Also, it kinda hard sets it.

**Comment by pcal43** [comment]
A lot of those messages are coming from the underlying git library - I don't have a lot of control over what it's doing.  It's either all-or-nothing, and I'd rather have it be all because something useful information is in there.

Filing as enhancement but really unlikely there's much to be done here.
