### ISSUE TITLE
ed25519 keys are not support in fasback-forge

### ISSUE THREAD

**Issue by pcal43** [pcal43/fastback#260]
Pulling my hair out figuring out how to get forge to allow Mina to load the i2p lib that enables this.

Until this is done, the only alternatives are:
* `set native-git-enabled true`
* use RSA keys, or something besides SSH

Note that github requires ed25519.

**Comment by Octelly** [comment]
Already got ``native-git-enabled`` set to ``true``, yet auth still fails. (I use Git all the time for various projects)
