### ISSUE TITLE
`set retention-policy` doc is out of date

### ISSUE THREAD

**Issue by shivangrathore** [pcal43/fastback#270]
/backup set retention fixed 5
[15:10:19] [Server thread/INFO]: Incorrect argument for command
[15:10:19] [Server thread/INFO]: ...ackup set retention fixed 5<--[HERE]

While commands without subommands work as expected
backup list
[15:05:20] [pool-3-thread-57/INFO]: 2023-09-02_16-14-36
[15:05:20] [pool-3-thread-57/INFO]: 2023-09-02_16-46-22
[15:05:20] [pool-3-thread-57/INFO]: 2023-09-03_10-04-23

**Comment by pcal43** [comment]
Ooops.  The doc is out of date.  The command is `set retention-policy`.

**Comment by ItsTeraBytes** [comment]
The instructions in the category "[Disk Space](https://pcal43.github.io/fastback/diskspace.html)" is also incorrect. It's using "set-retention" instead of "set retention-policy". It's also the same for "set-remote-retention" which should be "remote-retention-policy"

**Comment by pcal43** [comment]
> The instructions in the category "[Disk Space](https://pcal43.github.io/fastback/diskspace.html)" is also incorrect. It's using "set-retention" instead of "set retention-policy". It's also the same for "set-remote-retention" which should be "remote-retention-policy"

fixed, thanks
