### ISSUE TITLE
Mod can't find native git

### ISSUE THREAD

**Issue by KawaiiSelbst** [pcal43/fastback#287]
I have git and lfs installed on my computer and they are in Path, but the mod doesn't see them ![image](https://github.com/pcal43/fastback/assets/54507994/c17a472d-4e0a-476b-bd78-13c1bbff17e5)

Minecraft ver: 1.20.1
 Mod ver: 0.15.6

**Comment by pcal43** [comment]
please make support requests on the discord channel.  thanks.
https://discord.pcal.net
