### ISSUE TITLE
Feature request: Customize backup & restore directory for an easier file management

### ISSUE THREAD

**Issue by Silverteal** [pcal43/fastback#298]
For instances, some service providers may not provide easy access to the server file system, including /tmp dir, which makes it difficult to export restored saves(or remove the repository in case of cleaning the mod). Therefore, a customization might be helpful.

**Comment by pcal43** [comment]
you can `set restore-directory`.  does that not cover it?

**Comment by Silverteal** [comment]
> you can `set restore-directory`. does that not cover it?

Wow, that's it.
Due to some stupid reasons, I had not noticed that. Thank you for your help!

**Comment by pcal43** [comment]
> Due to some stupid reasons, I had not noticed that. Thank you for your help!

All good, no problem.
