### ISSUE TITLE
[enhancement] allow pointing to native git executable

### ISSUE THREAD

**Issue by Merith-TK** [pcal43/fastback#300]
The setup for individuals can be an bit weird from time to time, such as some Dedicated Server images (most) not containing an "native git binary", this config would allow the individual to point to an native git binary located on the system that may not be in `$PATH`, 

An example of this is I run my MC through an launcher that clears the $PATH variable to allow for isolated PATH's to be defined, as part of this, my git, which is located at `%USERPROFILE%/scoop/shims/git.exe` is not detectable by Minecraft/FastBack.

**Comment by pcal43** [comment]
It's a reasonable idea.  Unfortunately, git itself expects to be able to find itself on the PATH - it uses this to locate subcommands, most of which are discrete executables within the git distro.  

So, a solution like this will succeed in executing the core git executable but will then be unable to actually do anything useful (like `push` or `commit`).

**Comment by pcal43** [comment]
The other thing as well is that this setting couldn't be in the git config - that becomes a chicken-and-egg problem.

So really the only way would be either a mod-scoped properties file (which I'm fairly reluctant to add) or setting environment variables.  But in either case, it doesn't really seem like it is any easier than just setting the PATH correctly.

**Comment by Merith-TK** [comment]
The problem still includes Dedicated Servers, which it is NOT easier to set the PATH as we are not allowed to run generic shell scripts or alter runtime variables easily
![image](https://github.com/pcal43/fastback/assets/10422110/516c7224-15d0-4dac-bc5d-804a475324bd)
That startup command variable is a lie (I just tested it by replacing it with `bash start.sh` which contains an echo "Custom start worked" and an sleep 120), it acted as if there was no change to the startup command

**Comment by Alveel** [comment]
@Merith-TK did you find a solution? I happen to also be using scoop :)

**Comment by Merith-TK** [comment]
Other than setting your system level path to include git? nope. 

Cant even use it on my main server network because I run all that shit through `itzg/docker-minecraft` containers, which iirc dont have git installed in them...

Pcal, please just add the config, since this effectively makes it impossible to use on systems/environments where the PATH variable cannot be defined. 
HELL, you could legitimately have it so it downloads the appropriate standalone version of git and stores in the minecraft/server folder!
Thats what I do for my [code-server (`common/src/main/java/xyz/merith/CodeServer.java#L80`)](https://github.com/Merith-TK/mc-code-server/blob/main/common/src/main/java/xyz/merith/CodeServer.java#L80)

plus, you can append a value to PATH, which would resolve your concern about "git must be in path"
