### ISSUE TITLE
serverside messages are not localized on forge

### ISSUE THREAD

**Issue by skymkmk** [pcal43/fastback#313]
I am not forge mod developer, so I don't know the detail about the transmission between client and server. Considering this context: only server installed this mod and client not install it (because only server needs to backup the save file and the host do not want use hybrid server core). In this context, when client issue a command, server will response it surely, but it will only response key but not value, so user only can see the weird key "value". Surely most people will install mod both on server side and client side, and I fully understand why we response key, but is there anyway to render the response on the server side rather than client side?

After all, huge thanks to you and your masterpiece! :-)

**Comment by pcal43** [comment]
Right, this is known.  This works on fabric because it uses the server-translations-api
https://github.com/NucleoidMC/Server-Translations


I'm not sure exactly how to achieve that in Forge.  (I'm not really a forge mod developer, either.  :) )
