### ISSUE TITLE
Backups always fail, just stating that commit has failed.

### ISSUE THREAD

**Issue by YLlywelyn** [pcal43/fastback#328]
![2024-05-11_18 27 21](https://github.com/pcal43/fastback/assets/7080961/eba384b2-5dcf-4eb6-b4b6-d56fb45d5b70)

As shown in the title and screenshot.  I initialised backups using `/backup init` and it worked fine.  But anytime I try to use `/backup local` or `/backup full` it gives the error in the screenshot, "fastback.chat.commit-failed".

**Comment by Ceztio** [comment]
Try to add a git user.

```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

**Comment by Helcostr** [comment]
While the issue can probably be fixed via git, I am more interested in why the L10N failed:

![image](https://github.com/user-attachments/assets/6f9fabd8-ef68-4cd9-887c-f54f29b97ddd)

While I haven't familiarized myself with the code, raw printing vs localized printing seems to be the culprit.
