### ISSUE TITLE
Completely unusable due to missing protocol: "<unknown>"

### ISSUE THREAD

**Issue by Wekseth** [pcal43/fastback#341]
I'm new to github but I wanted to make this bc this plugin seems really nice but I'm entirely unable to use it due to this issue 

Terminal said "errors logged to" here, dont know if this is useful lol
[20240715T005854.0254407.log](https://github.com/user-attachments/files/16230212/20240715T005854.0254407.log)

**Comment by pcal43** [comment]
Please use the discord channel for support requests.
https://pcal43.github.io/fastback/
