### ISSUE TITLE
Install instructions really lacking clarity. 

### ISSUE THREAD

**Issue by Mister-Curious** [pcal43/fastback#343]
Im trying to use the Fastback mod, which according to [the Wiki](https://pcal43.github.io/fastback/) says that I need the following:

"As of version 0.17.1, Fastback requires that you have native `git `and `git-lfs` installed on your machine."

Under this is a link to Install Git:
Installing [git](https://github.com/git-lfs/git-lfs/wiki/Installation), however this link leads to the git-lfs page, and not the git page. On this page it says that the git-lfs requirements are `git >= 1.8.3.1` however, there is no link or any information on where to find this at all. 

I tried checking out the various git-lfs links and installed git-lfs, but without the git dependency it doesn't work. 

So I am here seeking clarification on where users can get the dependencies for this mod to work, specifically the git that is a prerequisite of git-lfs. 

Thank you.

**Comment by pcal43** [comment]
links fixed.  thanks for the report.
