### ISSUE TITLE
scheduled backups

### ISSUE THREAD

**Issue by pcal43** [pcal43/fastback#85]
embed quartz?  maybe overkill. just need some some basic configuration options.  every n minutes.  or every n ticks?

**Comment by KosmX** [comment]
Probably *every n minutes* would be enough.

**Comment by KosmX** [comment]
Something like this could work
```java

public class SchedulerUtil {

    private static final Timer timer = new Timer();

    public static void enable(int minutes) {
        timer.cancel();

        long millis = TimeUnit.MINUTES.toMillis(minutes);

        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                //however you back up the world
            }
        }, millis, millis);
    }

    public static void disable() {
        timer.cancel();
    }
}
```

**Comment by pcal43** [comment]
Thanks.  Yeah, I don't know that I'd want to spin up a whole thread just for that - might be better to just use the world tick callbacks.

But I'm going to do this one first:
https://github.com/pcal43/fastback/issues/119
which I think is probably more useful to most people.

**Comment by pcal43** [comment]
Would that work well enough for your case?  Autosave happens every 5 minutes, I believe.

**Comment by KosmX** [comment]
Timer thread is just waiting, it does not slow down anything.  

But backup after autosave makes sense too.  
Maybe you could tweak it to backup after *n* autosave.

**Comment by pcal43** [comment]
> Timer thread is just waiting, it does not slow down anything.

Sure but the overhead could add up if lots of mods are doing it.  Doing something tick-based where possible just seems like being a good citizen.

> Maybe you could tweak it to backup after n autosave.

That's a good idea.

**Comment by KosmX** [comment]
Listening to ticks has overhead too.

> Don't attempt to optimize your program it before working/knowing what is slowing it down.

**Comment by pcal43** [comment]
subsumed by #123 and #119
